type Response1 {
    message: String!,
    data: Category
}

type Response2 {
    message: String!,
    data: Products
}

type Response3 {
    message: String!,
    data: Orders
}

type Response4 {
    message: String!,
    data: OrderProduct
}

scalar Upload