type Response1 {
    message: String!,
    data: Category
}

type Response2 {
    message: String!
    data: Products
}

type Response3 {
    message: String!
    data: Orders
}

type Response4 {
    message: String!
    data: OrderProduct
}

type Response5 {
    message: String!
    token: String
    data: User
}


scalar Email
scalar Upload
scalar Contact
scalar Password