type Query {
    products: [Products!]!
}

type Products {
    product_id: Int!,
    category_id: Int!,
    product_name: String!,
    product_price: Int!,
    product_short_desc: String!,
    product_long_desc: String!,
    product_picture: String!
}