type Query {
    products(pagination: Pagination = {}): [Products!]!
    searchproducts(product_name:String! pagination: Pagination = {}): [Products!]!
}

type Mutation {
    addproduct (category_id: Int!
    product_name: String!
    product_price: Int!
    product_short_desc: String! 
    product_long_desc: String!
    file: Upload!
    ): Response2!

    deleteproduct (product_id: Int!): Response2!

    editproduct (
    product_id: Int!
    category_id: Int
    product_name: String
    product_price: Int
    product_short_desc: String
    product_long_desc: String
    file: Upload
    ): Response2!
}

type Products {
    product_id: Int!
    category_id: Int!
    product_name: String!
    product_price: Int!
    product_short_desc: String!
    product_long_desc: String!
    product_picture: String!
}